/**
 * Copyright Jeffrey Dungen 2018
 * Built on the reelyActive platform
 */


const PARETO_TOKEN = '';
const HUE_BRIDGE_IP = '';
const HUE_BRIDGE_USERNAME = '';
const LIGHTS = [ 1, 2, 3 ];
const RECEIVERS = [ '001bc50940810000', '001bc50940810001', '001bc50940810002' ];
const MAX_HUE_VALUE = 65000;
const MIN_HUE_VALUE = 42000;
const BREATHING_BASE_MILLISECONDS = 4000;
const UPDATE_INTERVAL_MILLISECONDS = 4000;
const SESSION_TIMEOUT_MILLISECONDS = 60000;


module.exports.PARETO_TOKEN = PARETO_TOKEN;
module.exports.HUE_BRIDGE_IP = HUE_BRIDGE_IP;
module.exports.HUE_BRIDGE_USERNAME = HUE_BRIDGE_USERNAME;
module.exports.LIGHTS = LIGHTS;
module.exports.RECEIVERS = RECEIVERS;
module.exports.MAX_HUE_VALUE= MAX_HUE_VALUE;
module.exports.MIN_HUE_VALUE = MIN_HUE_VALUE;
module.exports.BREATHING_BASE_MILLISECONDS = BREATHING_BASE_MILLISECONDS;
module.exports.UPDATE_INTERVAL_MILLISECONDS = UPDATE_INTERVAL_MILLISECONDS;
module.exports.SESSION_TIMEOUT_MILLISECONDS = SESSION_TIMEOUT_MILLISECONDS;
